name: purpose-dashboard
region: lon

services:
- name: web
  github:
    repo: SigmaAIAnalytics/Purpose-Dashboard
    branch: main
    deploy_on_push: true
  run_command: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: STREAMLIT_SERVER_HEADLESS
    value: "true"
  - key: STREAMLIT_SERVER_ENABLE_CORS
    value: "false"
  - key: SPACES_HIST_FILE
    value: "historical_spend.csv"
